event_name: RiceShop_StrangeWoman_Incident
once: true

trigger:
  town: KiyosuTown
  facility: RiceShop

script:
  - hero_think: "Strange... where is the rice shop owner?"

  - narration: "The shop is unusually quiet."
  - narration: "Behind the counter, a woman hurriedly stuffs something into her sleeve."

  - say:
      speaker: Hero
      listener: StrangeGirl
      text: "Excuse me... where is the shop owner?"

  - narration: "The woman freezes."

  - rename_say:
      speaker: StrangeGirl
      listener: Hero
      surname: Mysterious
      name: Woman
      text: "I... I was just leaving."

  - narration: "She slips past you, avoiding your gaze."

  - narration: "A moment later—"

  - say:
      speaker: RiceShopBoss
      listener: Hero
      text: "Ah! Sorry for the wait. I just came back from restocking."

  - narration: "The shop returns to normal."
